http {
  port = 8000
  port = ${?HTTP_PORT}
  logger = {
    http-header = false
    http-header = ${?HTTP_HEADER_LOG}
    http-body = false
    http-body = ${?HTTP_BODY_LOG}
  }
}

api {
  default-limit = 50
  default-limit = ${?API_DEFAULT_LIMIT}
  max-limit = 100
  max-limit = ${?API_MAX_LIMIT}
}

database {
  host = "127.0.0.1"
  host = ${?POSTGRES_HOST}
  port = 5432
  port = ${?POSTGRES_PORT}
  user = "postgres"
  user = ${?POSTGRES_USER}
  password = "postgres"
  password = ${?POSTGRES_PASSWORD}
  database = "jobs"
  database = ${?POSTGRES_DATABASE}
  enable-logging = true
  enable-logging = ${?POSTGRES_ENABLE_LOGGING}
}

kafka {
  bootstrap-servers = "localhost:9092"
  bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}

  topics {
    jobs-raw = "jobs.raw"
    jobs-raw = ${?KAFKA_TOPIC_JOBS_RAW}
  }

  consumer {
    group-id = "telegram-job-platform-etl"
    group-id = ${?KAFKA_CONSUMER_GROUP_ID}
    client-id = "telegram-job-platform-etl"
    client-id = ${?KAFKA_CONSUMER_CLIENT_ID}
    auto-offset-reset = "earliest"
    auto-offset-reset = ${?KAFKA_CONSUMER_AUTO_OFFSET_RESET}
    max-poll-records = 100
    max-poll-records = ${?KAFKA_CONSUMER_MAX_POLL_RECORDS}
    session-timeout = 30.seconds
    session-timeout = ${?KAFKA_CONSUMER_SESSION_TIMEOUT}
    heartbeat-interval = 3.seconds
    heartbeat-interval = ${?KAFKA_CONSUMER_HEARTBEAT_INTERVAL}
  }
}
